#!/usr/bin/ash

run_hook() {
    if [ -e /consolefont.psfu ]; then
	if [ -e /consolefont.psf ]; then
	    msg "\e[01;31m:: Both /consolefont.psf and /consolefont.psfu found, choosing .psfu\e[0m"
	fi
	msg ":: Loading console font..."
	setfont -C /dev/console /consolefont.psfu
    elif [ -e /consolefont.psf ]; then
	msg ":: Loading console font..."
	setfont -C /dev/console /consolefont.psf
    else
	msg "\e[01;31m:: No /consolefont.psf or /consolefont.psfu found, required by the hook consolefont\e[0m"
    fi
}

